#showAction: info about the user and the group projects  
tangara_project_show:
    path:  /show/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:show, projectId: false }        

tangara_project_list:
    path:  /list
    defaults: { _controller: TangaraCoreBundle:Project:list }

tangara_project_edit:
    path:  /edit/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:edit, projectId: false }

tangara_project_select:
    path:  /select/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:select}
    requirements:
        projectId:  \d+

tangara_project_create:
    path: /create
    defaults: { _controller: TangaraCoreBundle:Project:create}

tangara_project_published:
    path:  /published
    defaults: { _controller: TangaraCoreBundle:Project:published}

tangara_project_execute:
    path:  /execute/{projectId}
    defaults: { _controller: TangaraCoreBundle:Project:execute, projectId: false}
